# Generated by Django 6.0.6 on 2026-06-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Professional IT Engineer', max_length=150)),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=100)),
                ('email', models.EmailField(default='er.bombdrbk@gmail.com', max_length=254)),
                ('company', models.CharField(default='ADBL', max_length=100)),
                ('interests', models.CharField(default='AI, Blockchain, Cloud, DevSecOps', max_length=255)),
                ('profile_image', models.CharField(default='/profile.jpg', max_length=255)),
            ],
            options={
                'verbose_name': 'About Data',
                'verbose_name_plural': 'About Data',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Er. Bom Bahadur BK', max_length=100)),
                ('phrases', models.JSONField(default=list, help_text='JSON array of typing text phrases')),
                ('tagline', models.TextField(default='Passionate about building scalable web applications and optimizing developer workflows.')),
                ('cv_url', models.CharField(default='#', max_length=255)),
            ],
            options={
                'verbose_name': 'Hero Data',
                'verbose_name_plural': 'Hero Data',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list, help_text='JSON array of tech tags')),
                ('image_url', models.CharField(max_length=255)),
                ('link', models.CharField(default='#', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Ongoing', help_text='e.g. Active, Completed, Published', max_length=100)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.CharField(default='June 2026', max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.skillcategory')),
            ],
        ),
    ]
