# Generated by Django 4.2.27 on 2026-06-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdata',
            name='profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
