# Generated by Django 4.2.27 on 2026-06-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutdata_profile_image_file_blogpost_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutdata',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
    ]
